"""Add ApiKeys table for HTTPS Git authentication

Adds the ApiKeys table, which stores SHA-256 hashed API keys that users can
create to authenticate git push operations over HTTPS (as an alternative to SSH
keys). Each key is tied to a user and tracks last-used metadata.

Also fixes pre-existing nullable drift on composite primary key columns in
PackageGroups, PackageKeywords, and PackageLicenses to align the database with
the schema definitions.

Revision ID: 1752f51452c4
Revises: f2701a76f4a9
Create Date: 2026-04-28 14:46:19.255394

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1752f51452c4"
down_revision = "f2701a76f4a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ApiKeys",
        sa.Column("ID", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("UserID", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("KeyHash", sa.String(length=64), nullable=False),
        sa.Column(
            "Name", sa.String(length=128), server_default=sa.text("''"), nullable=False
        ),
        sa.Column(
            "CreatedTS",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("LastUsedTS", mysql.BIGINT(unsigned=True), nullable=True),
        sa.Column("LastUsedIPAddress", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["UserID"], ["Users.ID"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ID"),
        sa.UniqueConstraint("KeyHash"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_bin",
        mysql_engine="InnoDB",
    )
    op.create_index("ApiKeysUserID", "ApiKeys", ["UserID"], unique=False)
    op.alter_column(
        "PackageGroups",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageGroups",
        "GroupID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "PackageLicenses",
        "LicenseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageLicenses",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageKeywords",
        "PackageBaseID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageGroups",
        "GroupID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.alter_column(
        "PackageGroups",
        "PackageID",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        nullable=False,
    )
    op.drop_index("ApiKeysUserID", table_name="ApiKeys")
    op.drop_table("ApiKeys")
    # ### end Alembic commands ###
